#!/usr/bin/env python3

import os
import pathlib
import shutil
import subprocess
import sys


def main():
    assert len(sys.argv) > 1, "please select a target from 'install', 'uninstall', 'bootstrap-agent', 'bootstrap-job', 'clean'"
    target = sys.argv[1]
    blockchain_path = pathlib.Path(__file__).absolute().parent.parent.joinpath("blockchain")
    blockchain_build_path = blockchain_path.joinpath("build")
    blockchain_node_path = blockchain_path.joinpath("node_modules")
    agent_json_src_path = blockchain_node_path.joinpath("singularitynet-alpha-blockchain", "Agent.json")
    agent_json_dest_path = pathlib.Path(__file__).absolute().parent.parent.joinpath("snetd_alpha", "resources",
                                                                                    "Agent.json")
    if target == "install":
        subprocess.call(["npm", "install"], cwd=blockchain_path)
        shutil.copy(agent_json_src_path, agent_json_dest_path)
    elif target == "create-mnemonic":
        subprocess.call(["npm", "run", "create-mnemonic"], cwd=blockchain_path)
    elif target == "bootstrap-agent":
        subprocess.call(["npm", "run", "migrate"], cwd=blockchain_path)
        subprocess.call(["npm", "run", "create-agent"], cwd=blockchain_path)
    elif target == "bootstrap-job":
        subprocess.call(["npm", "run", "create-job"], cwd=blockchain_path)
        subprocess.call(["npm", "run", "fund-job"], cwd=blockchain_path)
        subprocess.call(["npm", "run", "sign-job"], cwd=blockchain_path)
    elif target == "uninstall":
        try:
            shutil.rmtree(blockchain_node_path)
            os.remove(agent_json_dest_path)
        except FileNotFoundError:
            pass
    elif target == "clean":
        try:
            shutil.rmtree(blockchain_build_path)
        except FileNotFoundError:
            pass


if __name__ == "__main__":
    main()
