#!/usr/bin/env python3

import pathlib
import subprocess

import jsonrpcclient
import time

from snetd_alpha import configuration as config


def main():
    scripts_path = pathlib.Path(__file__).absolute().parent
    node_path = pathlib.Path(__file__).absolute().parent.parent.joinpath("blockchain", "node_modules")
    root_path = scripts_path.parent
    subprocess.call(["./blockchain", "install-dev"], cwd=scripts_path)
    ganache_p = subprocess.Popen(
        ["./.bin/ganache-cli", "-m", "orphan wheel horse track deer rotate crew heart satoshi abstract modify warrior"],
        cwd=node_path)
    subprocess.call(["./blockchain", "clean"], cwd=scripts_path)
    subprocess.call(["rm", "-rf", "snetd.db"], cwd=root_path)
    snetd_p = subprocess.Popen(["snetd"], cwd=root_path)
    subprocess.call(["./blockchain", "bootstrap"], cwd=scripts_path)

    time.sleep(config.POLL_SLEEP_SECS * 1.5)

    try:
        jsonrpcclient.request("http://127.0.0.1:{}".format(config.SERVER_PORT), "whatever",
                              job_address="0x6b366d0aba92a794dec62032b0f5b5a9f2e23fb7",
                              job_signature="0x0c75552adad204dfc53e8354c4b31a0af31b99eefdfff7620d517efcbab799d07c14794e39f413a4e4db5dbdf9a9be0af53cc7fc5d290959402e510d89d7e59e01")
        time.sleep(config.POLL_SLEEP_SECS * 1.5)
    except Exception as e:
        print(e)
    subprocess.call(["rm", "-rf", "snetd.db"], cwd=root_path)
    snetd_p.terminate()
    ganache_p.terminate()


if __name__ == "__main__":
    main()
